apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary
spec:
  selector:
    matchLabels:
      app: motd
  replicas: 2
  template:
    metadata:
      labels:
        app: motd
    spec:
      containers:
      - name: motd
        image: yukirona/motd-docker
        env:
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: eric-configmap
              key: message

