apiVersion: apps/v1
kind: Deployment
metadata:
  name: eric-canary
spec:
  selector:
    matchLabels:
      app: motd-canary
  replicas: 2
  template:
    metadata:
      labels:
        app: motd-canary
        env: prod
    spec:
      containers:
      - name: motd
        image: yukirona/motd-docker
        env:
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: eric-configmap
              key: message

